//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAmaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIHOC
    {
        public string MABH { get; set; }
        public string TENBH { get; set; }
        public string NOIDUNGBH { get; set; }
        public string MAKHOAHOC { get; set; }
    
        public virtual KHOAHOC KHOAHOC { get; set; }
    }
}
