//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAmaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKIKHOAHOC
    {
        public int ID_DANGKI { get; set; }
        public string USERNAME_DK { get; set; }
        public string MAKHOAHOC { get; set; }
        public string TENKHOAHOC { get; set; }
        public string TG { get; set; }
        public string ANHKH { get; set; }
        public Nullable<System.DateTime> TIME_DK { get; set; }
    
        public virtual KHOAHOC KHOAHOC { get; set; }
    }
}
