//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAmaz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CODEAMAZ : DbContext
    {
        public DB_CODEAMAZ()
            : base("name=DB_CODEAMAZ")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUDE> CHUDEs { get; set; }
        public virtual DbSet<KHOAHOC> KHOAHOCs { get; set; }
        public virtual DbSet<LOGIN> LOGINs { get; set; }
        public virtual DbSet<QUYEN_USER> QUYEN_USER { get; set; }
        public virtual DbSet<CHANGE_PASS> CHANGE_PASS { get; set; }
        public virtual DbSet<DANGKIKHOAHOC> DANGKIKHOAHOCs { get; set; }
        public virtual DbSet<BAIHOC> BAIHOCs { get; set; }
        public virtual DbSet<BINHLUANKHOAHOC> BINHLUANKHOAHOCs { get; set; }
    }
}
