//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAmaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOAHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHOAHOC()
        {
            this.DANGKIKHOAHOCs = new HashSet<DANGKIKHOAHOC>();
            this.BAIHOCs = new HashSet<BAIHOC>();
            this.BINHLUANKHOAHOCs = new HashSet<BINHLUANKHOAHOC>();
        }
    
        public string MAKH { get; set; }
        public string TENKH { get; set; }
        public string TACGIA { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public string ANHKHOAHOC { get; set; }
        public string MUCTIEU { get; set; }
        public string MOTANGAN { get; set; }
        public string MOTAFULL { get; set; }
        public string MACD { get; set; }
        public Nullable<int> SOBAIGIANG { get; set; }
        public string ANHMOTA { get; set; }
    
        public virtual CHUDE CHUDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKIKHOAHOC> DANGKIKHOAHOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIHOC> BAIHOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUANKHOAHOC> BINHLUANKHOAHOCs { get; set; }
    }
}
